spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/old_people?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# Mybatis
mybatis:
  type-aliases-package: com.sm.graduation.nurse.pojo,com.sm.graduation.usr.pojo,com.sm.graduation.health.pojo,com.sm.graduation.high.pojo,com.sm.graduation.medication.pojo,com.sm.graduation.food.pojo,com.sm.graduation.out.pojo,com.sm.graduation.checkin.pojo,com.sm.graduation.dormitory.pojo,com.sm.graduation.accident.pojo,com.sm.graduation.visitor.pojo,com.sm.graduation.older.pojo,com.sm.graduation.nursing.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

